# Generated by Django 5.1.4 on 2026-04-28 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_mentale', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='charge mentale')),
                ('charge_physique', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='charge physique')),
                ('duree', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='durée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='date de mise à jour')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='activites.activite', verbose_name='activité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_maj'],
                'constraints': [models.UniqueConstraint(fields=('user', 'activite'), name='unique_evaluation_par_user_activite'), models.CheckConstraint(condition=models.Q(('charge_mentale__gte', 1), ('charge_mentale__lte', 5), ('charge_physique__gte', 1), ('charge_physique__lte', 5), ('duree__gte', 1), ('duree__lte', 5)), name='evaluation_valeurs_dans_echelle')],
            },
        ),
    ]
