# Generated by Django 5.1.4 on 2026-04-27 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='nom')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'Foyer',
                'verbose_name_plural': 'Foyers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MembreFoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrivee', models.DateField(auto_now_add=True, verbose_name="date d'arrivée")),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='foyer.foyer', verbose_name='foyer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membrefoyer', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Membre du foyer',
                'verbose_name_plural': 'Membres du foyer',
                'ordering': ['date_arrivee'],
            },
        ),
    ]
