# Generated by Django 5.1.4 on 2026-04-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foyer", "0004_alter_foyer_cree_par_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("acceptee", "Acceptée"),
                    ("annulee", "Annulée"),
                    ("expiree", "Expirée"),
                ],
                default="en_attente",
                max_length=20,
                verbose_name="statut",
            ),
        ),
    ]
