# Generated by Django 5.1.4 on 2026-04-28 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foyer', '0005_alter_invitation_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, default='', verbose_name='contenu')),
                ('derniere_consultation', models.DateTimeField(blank=True, null=True, verbose_name='dernière consultation par le propriétaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='foyer.membrefoyer', verbose_name='membre')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrait', models.TextField(verbose_name='extrait commenté')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_notes', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='notes.note', verbose_name='note')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
            },
        ),
    ]
