# Generated by Django 5.1.4 on 2026-04-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activites', '0001_initial'),
        ('foyer', '0005_alter_invitation_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodePlanification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes_planification', to='foyer.foyer', verbose_name='foyer')),
            ],
            options={
                'verbose_name': 'Période de planification',
                'verbose_name_plural': 'Périodes de planification',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(verbose_name='jour')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='activites.activite', verbose_name='activité')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='foyer.membrefoyer', verbose_name='membre')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planification.periodeplanification', verbose_name='période')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['jour', 'date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodeplanification',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='periode_planification_dates_coherentes'),
        ),
    ]
