# Generated by Django 5.1.4 on 2026-04-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foyer', '0005_alter_invitation_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, verbose_name='nom')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='foyer.foyer', verbose_name='foyer')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='titre')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='foyer.foyer', verbose_name='foyer')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='activites.categorie', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['categorie__nom', 'titre'],
            },
        ),
        migrations.AddConstraint(
            model_name='categorie',
            constraint=models.UniqueConstraint(fields=('foyer', 'nom'), name='unique_categorie_par_foyer_nom'),
        ),
    ]
